version: "3"
services:
  jupyter-lab:
    # restart: on-failure
    networks:
      - jupyter_net
    build: ./jupyter-lab
    image: my-jupyter/lab:1.1
    expose:
      - 8888
    volumes:
      - "./workspace:/home/jovyan/work"
    command: start.sh jupyter lab

  caddy:
    # restart: on-failure
    networks:
      - jupyter_net
    build: ./caddy
    depends_on:
      - jupyter-lab
    volumes:
      - type: bind
        source: /etc/letsencrypt/live/jupyter.taraxacum.ink/fullchain.pem
        target: /etc/caddy/fullchain.pem
      - type: bind
        source: /etc/letsencrypt/live/jupyter.taraxacum.ink/privkey.pem
        target: /etc/caddy/privkey.pem
    ports:
      - 13080:80
      - 13443:443

networks:
  jupyter_net:
